### ISSUE TITLE
Error in keeping a seperate items.cljc

### ISSUE THREAD

**Issue by abhi18av** [facundoolano/advenjure-example#3]
Hey, so I've been experimenting a bit more and I tried to separate out all the items into a different file i.e. from `rooms.cljc` to `items.cljc` and export the items much like `npc-dialog` in `dialog.cljc`.

Imported these as 

``` clojure
example.items :refer [my-items]
```

But while compiling, I run into the following error message ( shortened for brevity). If it's not too troublesome, could you please show me around - I do miss the documentation)

```
Exception in thread "main" java.lang.ClassCastException: advenjure.items.Item cannot be cast to clojure.lang.IFn, compiling:(items.cljc:53:9)
```

**Comment by facundoolano** [comment]
Can you show the contents of items.cljc ?

(as a side-note, remember this is just the repository for the example game. The documentation is in the [advenjure repository](https://github.com/facundoolano/advenjure))

**Comment by abhi18av** [comment]
Here's the  [Gist](https://gist.github.com/abhi18av/b7b83114a3691b0394c9e9bf3b04c30b)

Yeah, I do know about the [advenjure](https://github.com/facundoolano/advenjure) but the `docs` don't say much. Would you like some help? I'd love to be involved:)

**Comment by facundoolano** [comment]
Your problem is in line 53 as the error suggested. You are trying to call the "novel" item. Just remove that definition and require each item by its name in the other file: 

``` clojure
(:require [example.items :refer [novel piggybank bottle bed drawer]])
```

The dialog definition you took as an example is different, the `dialog` macro can take any number of dialogs and pack them into a new one. Items and Rooms are just clojure records.

About helping, Pull Requests are welcome!

**Comment by abhi18av** [comment]
Ah, I see. Silly mistakes :)

I'll start with documentation then, btw how about [Marginalia](https://github.com/gdeer81/marginalia) for documentation?

Or what are your ideas on documentation for advenjure?

**Comment by facundoolano** [comment]
To be honest, I'm not a fan of code generated documentation. At least in medium sized projects I prefer to keep the documentation manually, and just use use the github README or the wiki if it gets too big.

I think the current readme is good enough to get started, what do you feel is missing?

**Comment by abhi18av** [comment]
Most of all, I felt the lack of colors! Colors would really make things easy on the eyes - as in all the `verbs` should be in colors, you know things like that. Perhaps, there's a way to use colors within JLine or [Jansi](https://github.com/fusesource/jansi)

The terminal as a UI is beautifully limited, so lots of scope for improvement.

Actually I'm into mindmaps and language learning, plus I really like Clojure - I feel this can be used in a beautiful way for learning things.

*\* So, you're thinking of this as short term thing? Just that, with good documentation it'd be easier for people to learn and extend the code faster - though I'm just a n00b at these things, can't be too sure.

**Comment by abhi18av** [comment]
I've found 4 Clojure libraries, in the order of decreasing stars

https://github.com/AvisoNovate/pretty
https://github.com/ams-clj/clansi
https://github.com/ibdknox/colorize
https://github.com/xsc/jansi-clj
